// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.idearoo.domain;

import com.idearoo.domain.PostDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PostIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PostIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PostIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PostIntegrationTest: @Transactional;
    
    @Autowired
    private PostDataOnDemand PostIntegrationTest.dod;
    
    @Test
    public void PostIntegrationTest.testCountPosts() {
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to initialize correctly", dod.getRandomPost());
        long count = com.idearoo.domain.Post.countPosts();
        org.junit.Assert.assertTrue("Counter for 'Post' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PostIntegrationTest.testFindPost() {
        com.idearoo.domain.Post obj = dod.getRandomPost();
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to provide an identifier", id);
        obj = com.idearoo.domain.Post.findPost(id);
        org.junit.Assert.assertNotNull("Find method for 'Post' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Post' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PostIntegrationTest.testFindAllPosts() {
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to initialize correctly", dod.getRandomPost());
        long count = com.idearoo.domain.Post.countPosts();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Post', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.idearoo.domain.Post> result = com.idearoo.domain.Post.findAllPosts();
        org.junit.Assert.assertNotNull("Find all method for 'Post' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Post' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PostIntegrationTest.testFindPostEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to initialize correctly", dod.getRandomPost());
        long count = com.idearoo.domain.Post.countPosts();
        if (count > 20) count = 20;
        java.util.List<com.idearoo.domain.Post> result = com.idearoo.domain.Post.findPostEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Post' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Post' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PostIntegrationTest.testFlush() {
        com.idearoo.domain.Post obj = dod.getRandomPost();
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to provide an identifier", id);
        obj = com.idearoo.domain.Post.findPost(id);
        org.junit.Assert.assertNotNull("Find method for 'Post' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPost(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Post' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PostIntegrationTest.testMerge() {
        com.idearoo.domain.Post obj = dod.getRandomPost();
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to provide an identifier", id);
        obj = com.idearoo.domain.Post.findPost(id);
        boolean modified =  dod.modifyPost(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.idearoo.domain.Post merged = (com.idearoo.domain.Post) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Post' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PostIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to initialize correctly", dod.getRandomPost());
        com.idearoo.domain.Post obj = dod.getNewTransientPost(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Post' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Post' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PostIntegrationTest.testRemove() {
        com.idearoo.domain.Post obj = dod.getRandomPost();
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Post' failed to provide an identifier", id);
        obj = com.idearoo.domain.Post.findPost(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Post' with identifier '" + id + "'", com.idearoo.domain.Post.findPost(id));
    }
    
}
